### ISSUE TITLE
Thanks for this wonderful Package - Issue Notification

### ISSUE THREAD

**Issue by gjsjy** [hota1024/twict#2]
Hi @hota1024,

How are you?

I have found a couple of minor issues. All of them are typos in the definition, Entities - poll, DirectMessageEvent - sender_id . And in the index file - EVENT_TYPES - one of them is causing failure, direct_message_mark_read_events.

`const getEventType = (event) => {
    for (const type of EVENT_TYPES) {
        if (isExpectEventType(event, type)) {
            return type;
        }
    }
    throw new Error(`getEventType error: unknown event type.`);
};`

Thanks again for your work.

I appreciate it if you can address this issue when you find the time.

Thanks,

Gj

**Comment by nnx0r** [comment]
I get issue with unknown event and 500 ISE. 
`Error: getEventType error: unknown event type.`

**Comment by hota1024** [comment]
Hi @gjsjy @dvlden 
Thanks for the issue.
I'm sorry. I have been busy with college exams and other projects.
I hope to fix the code soon.

**Comment by hota1024** [comment]
Merged the modified code.
Please update your package for each project as we have released it as version 0.0.8.
Thank you.
https://www.npmjs.com/package/twict
